### ISSUE TITLE
Sending '=' inside of any send function doesn't seem to work

### ISSUE THREAD

**Issue by Frankushima** [spyoungtech/ahk#96] opened 2020-08-15 04:22 UTC
I'm creating an Auto-Login script for a game, but it seems that sending an equal sign with any function causes it to not work.
Ex:
ahk.send_raw('=')
ahk.send_input('=')
ahk.send('=')
ahk.type('=')
ahk.send_play('=')

None of these send an equal sign, nor throw an exception. 

In fact, adding something after the equal sign doesn't change anything.
Ex: ahk.type('=hello')
This also doesn't send anything.

Am I doing something wrong?

Sorry about the weird formatting. I'm new to GitHub

**Comment by spyoungtech** [comment] 2020-08-26 13:09
Reproduced this and confirmed this is a bug. `ahk.type` should perform any necessary escapes for the user, but in this case it does not. `ahk.send` and other variants require users to escape strings themselves, e.g. `Send {=}`

`send_raw` seems to exhibit this bug because the template fails to include a `,` after `SendRaw`

I should be able to get this fixed in the next release.

**Comment by spyoungtech** [comment] 2020-09-07 12:43
Resolved in #97

**Closed** 2020-09-07 12:43 UTC
Labels: bug

**Comment by spyoungtech** [comment] 2020-09-07 13:19
Fix released in v0.10.0
