### ISSUE TITLE
CapsLock issues with key_state() and key_press()

### ISSUE THREAD

**Issue by Glutenberg** [spyoungtech/ahk#100] opened 2020-09-13 20:44 UTC
**Issues with key_press():**
key_press will toggle CapsLock on but not off
Function works as expected for NumLock and ScrollLock

**Issues with key_state():**
key_state will not detect if CapsLock is toggled or not. 
Issue is consistent with NumLock and ScrollLock. 
key_state will detect if the key is currently depressed. 
Possibly an issue with passing mode argument.

**Comment by spyoungtech** [comment] 2020-09-15 23:49
Thanks for reporting this @Glutenberg 

> key_press will toggle CapsLock on but not off. 


Hmm. This is odd to me. I'll check this out and confirm the behavior. In the meantime, I would double-check that you're using the latest version of AHK.

From a quick glance, it may be necessary to use [SetCapsLockState](https://www.autohotkey.com/docs/commands/SetNumScrollCapsLockState.htm) for this. But I wonder why the behavior is different compared to NumLock/ScrollLock. Sounds almost like an AHK bug :-)

Under the hood, `key_press` uses `SendInput`.  I'll also check to see if I can reproduce this behavior just using a plain AHK script without this library. That would also help diagnose whether there is an issue to be fixed in the wrapper or not.

If the issue is in AHK and not the wrapper, I think the next logical thing would be to implement `SetCapsLockState` (and related functions) in the wrapper.

> Possibly an issue with passing mode argument.

Have you tried passing in the `mode=` keyword argument? For the behavior you're looking for with CapsLock, NumLock and ScrollLock you should pass in `mode=T`, I believe. [reference](https://www.autohotkey.com/docs/commands/GetKeyState.htm).

```python
ahk.key_state('CapsLock', mode='T')
```

**Comment by spyoungtech** [comment] 2020-09-15 23:57
Just saw the PR #101 for the Mode fix. Merged in!

**Comment by Glutenberg** [comment] 2020-09-16 00:02
I solved the problem and submitted a pull request. SetCapsLockState needed to be implemented. It may be messy, not really a programmer but I tried :)

**Comment by spyoungtech** [comment] 2020-09-16 00:09
Thanks a bunch for submitting the pull request, that helps a lot. #102 is just awaiting a small change and I can get that merged in as well and plan to release it to PyPI in the next day or so :-)

**Comment by spyoungtech** [comment] 2020-09-17 20:01
Resolved by #102

**Closed by spyoungtech** 2020-09-17 20:01 UTC
